DMQuyetTien/QuyetTienWeb/Areas/Admin/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuyetTienWeb.Models;
using System.Transactions;

namespace QuyetTienWeb.Areas.Admin.Controllers
{
    public class ProductAdminController : Controller
    {
        CS4PEEntities db = new CS4PEEntities();
        //
        // GET: /Admin/ProductAdmin/
        public ActionResult Index()
        {
            var product = db.BangSanPhams.OrderByDescending(x => x.id).ToList();
            return View(product);
        }
        // GET: /Admin/AdminProduct/Create
        public ActionResult Create()
        {
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.BangSanPhams.Add(model);
                    db.SaveChanges();

                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null && Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);
                        scope.Complete();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("HinhAnh", "Chưa có hình ảnh sản phẩm");
                    }
                }
            }

            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        private void CheckBangSanPham(BangSanPham model)
        {
            if (model.GiaGoc < 0)
            {
                ModelState.AddModelError("GiaGoc", "Giá gốc phải lớn hơn 0");
            }
            if (model.GiaBan < 0)
            {
                ModelState.AddModelError("GiaBan", "Giá bán phải lớn hơn 0");
            }
            if (model.GiaGop < 0)
            {
                ModelState.AddModelError("GiaGop", "Giá trả góp phải lớn hơn 0");
            }
        }
	}
}

DMQuyetTien/QuyetTienWeb/Controllers/BangSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuyetTienWeb.Models;
using System.Transactions;

namespace QuyetTienWeb.Controllers
{
    public class BangSanPhamController : Controller
    {
        private CS4PEEntities db = new CS4PEEntities();

        // GET: /BangSanPham/
        public ActionResult Index()
        {
            var bangsanphams = db.BangSanPhams.Include(b => b.LoaiSanPham);
            return View(bangsanphams.ToList());
        }

        // GET: /BangSanPham/Details/5
        public FileResult Details(string id)
        {
            var path = Server.MapPath("~/App_Data/" + id);
            return File(path, "images");
        }

        // GET: /BangSanPham/Create
        public ActionResult Create()
        {
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai");
            return View();
        }

        // POST: /BangSanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.BangSanPhams.Add(model);
                    db.SaveChanges();

                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null && Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);
                        scope.Complete();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("HinhAnh", "Chưa có hình ảnh sản phẩm");
                    }
                }
            }

            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // GET: /BangSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", bangsanpham.Loai_id);
            return View(bangsanpham);
        }

        // POST: /BangSanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BangSanPham bangsanpham)
        {
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + bangsanpham.id;
                    if (Request.Files["HinhAnh"] != null &&
                        Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);
                        db.Entry(bangsanpham).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                    
                
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", bangsanpham.Loai_id);
            return View(bangsanpham);
        }

        // GET: /BangSanPham/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            return View(bangsanpham);
        }

        private void CheckBangSanPham(BangSanPham model)
        {
            if (model.GiaGoc < 0)
            {
                ModelState.AddModelError("GiaGoc", "Giá gốc phải lớn hơn 0");
            }
            if (model.GiaBan < 0)
            {
                ModelState.AddModelError("GiaBan", "Giá bán phải lớn hơn 0");
            } 
            if (model.GiaGop < 0)
            {
                ModelState.AddModelError("GiaGop", "Giá trả góp phải lớn hơn 0");
            }
        }

        // POST: /BangSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            db.BangSanPhams.Remove(bangsanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DMQuyetTien/QuyetTienWeb/Areas/Admin/Views/ProductAdmin/Create.cshtml
@model QuyetTienWeb.Models.BangSanPham
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "BangSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>BangSanPham</h4>*@
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "Mã sản phẩm :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, "Tên sản phẩm :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "Loại :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Loai_id", (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, "Giá gốc :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, "Giá góp :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Số lượng tồn :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("HinhAnh", "Hinh san pham :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", "", new { type = "file", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img style="width: 300px" id="HinhSanPham" src="" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#HinhSanPham').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#HinhAnh").change(function () {
            readURL(this);
        });
    </script>
}

DMQuyetTien/QuyetTienWeb/Areas/Admin/Views/ProductAdmin/Index.cshtml
@model IEnumerable<QuyetTienWeb.Models.BangSanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Table Product
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Product Code</th>
                        <th>Product Name</th>
                        <th>Sale Price</th>
                        <th>Origin Price</th>
                        <th>Installment Price</th>
                        <th>Quantity</th>
                        <th>Product Type</th>
                        <th>Option</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Product Code</th>
                        <th>Product Name</th>
                        <th>Sale Price</th>
                        <th>Origin Price</th>
                        <th>Installment Price</th>
                        <th>Quantity</th>
                        <th>Product Type</th>
                        <th>Option</th> 
                    </tr>
                </tfoot>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaSP)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenSP)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GiaBan)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GiaGoc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GiaGop)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SoLuongTon)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LoaiSanPham.TenLoai)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.id }, new { @class = "btn btn-success" })  
                                @Html.ActionLink("Details", "Details", new { id = item.id }, new { @class="btn btn-info"})
                                @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>